version: '3.8'

name: url-shortener-app
services:
  postgres:
    image: postgres:18.1-alpine
    container_name: shortener-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shortener-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shortener-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shortener-network:
    driver: bridge

volumes:
  postgres_data:
